In [1]:
#Importing libraries
import pandas as pd
import numpy as np

In [2]:
missing_values = ["n/a", "na", "--", ""]

df_train = pd.read_csv('train.csv', na_values = missing_values)
df_train['type'] = 'analysis'
df_test = pd.read_csv('test.csv', na_values = missing_values)
df_test['SalePrice'] = ""
df_test['type'] = 'scoring'

df = pd.concat([df_train, df_test])

In [3]:
numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']

df_cont = df_train.select_dtypes(include=numerics)

In [4]:
df_cont

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
0,1,60,65.0,8450,7,5,2003,2003,196.0,706,...,0,61,0,0,0,0,0,2,2008,208500
1,2,20,80.0,9600,6,8,1976,1976,0.0,978,...,298,0,0,0,0,0,0,5,2007,181500
2,3,60,68.0,11250,7,5,2001,2002,162.0,486,...,0,42,0,0,0,0,0,9,2008,223500
3,4,70,60.0,9550,7,5,1915,1970,0.0,216,...,0,35,272,0,0,0,0,2,2006,140000
4,5,60,84.0,14260,8,5,2000,2000,350.0,655,...,192,84,0,0,0,0,0,12,2008,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,62.0,7917,6,5,1999,2000,0.0,0,...,0,40,0,0,0,0,0,8,2007,175000
1456,1457,20,85.0,13175,6,6,1978,1988,119.0,790,...,349,0,0,0,0,0,0,2,2010,210000
1457,1458,70,66.0,9042,7,9,1941,2006,0.0,275,...,0,60,0,0,0,0,2500,5,2010,266500
1458,1459,20,68.0,9717,5,6,1950,1996,0.0,49,...,366,0,112,0,0,0,0,4,2010,142125
1459,1460,20,75.0,9937,5,6,1965,1965,0.0,830,...,736,68,0,0,0,0,0,6,2008,147500

In [19]:
df_cont.isnull().sum()

MSSubClass       0
LotFrontage      0
LotArea          0
OverallQual      0
OverallCond      0
YearBuilt        0
YearRemodAdd     0
MasVnrArea       0
BsmtFinSF1       0
BsmtFinSF2       0
BsmtUnfSF        0
TotalBsmtSF      0
1stFlrSF         0
2ndFlrSF         0
LowQualFinSF     0
GrLivArea        0
BsmtFullBath     0
BsmtHalfBath     0
FullBath         0
HalfBath         0
BedroomAbvGr     0
KitchenAbvGr     0
TotRmsAbvGrd     0
Fireplaces       0
GarageYrBlt      0
GarageCars       0
GarageArea       0
WoodDeckSF       0
OpenPorchSF      0
EnclosedPorch    0
3SsnPorch        0
ScreenPorch      0
PoolArea         0
MiscVal          0
MoSold           0
YrSold           0
SalePrice        0
dtype: int64

In [6]:
df_cont = df_cont.fillna(df_cont.median())

In [7]:
df_cont.isnull().sum()

Id               0
MSSubClass       0
LotFrontage      0
LotArea          0
OverallQual      0
OverallCond      0
YearBuilt        0
YearRemodAdd     0
MasVnrArea       0
BsmtFinSF1       0
BsmtFinSF2       0
BsmtUnfSF        0
TotalBsmtSF      0
1stFlrSF         0
2ndFlrSF         0
LowQualFinSF     0
GrLivArea        0
BsmtFullBath     0
BsmtHalfBath     0
FullBath         0
HalfBath         0
BedroomAbvGr     0
KitchenAbvGr     0
TotRmsAbvGrd     0
Fireplaces       0
GarageYrBlt      0
GarageCars       0
GarageArea       0
WoodDeckSF       0
OpenPorchSF      0
EnclosedPorch    0
3SsnPorch        0
ScreenPorch      0
PoolArea         0
MiscVal          0
MoSold           0
YrSold           0
SalePrice        0
dtype: int64

In [8]:
df_cont.drop(['Id'], axis=1, inplace=True)

In [9]:
df_cont

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
0,60,65.0,8450,7,5,2003,2003,196.0,706,0,...,0,61,0,0,0,0,0,2,2008,208500
1,20,80.0,9600,6,8,1976,1976,0.0,978,0,...,298,0,0,0,0,0,0,5,2007,181500
2,60,68.0,11250,7,5,2001,2002,162.0,486,0,...,0,42,0,0,0,0,0,9,2008,223500
3,70,60.0,9550,7,5,1915,1970,0.0,216,0,...,0,35,272,0,0,0,0,2,2006,140000
4,60,84.0,14260,8,5,2000,2000,350.0,655,0,...,192,84,0,0,0,0,0,12,2008,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,60,62.0,7917,6,5,1999,2000,0.0,0,0,...,0,40,0,0,0,0,0,8,2007,175000
1456,20,85.0,13175,6,6,1978,1988,119.0,790,163,...,349,0,0,0,0,0,0,2,2010,210000
1457,70,66.0,9042,7,9,1941,2006,0.0,275,0,...,0,60,0,0,0,0,2500,5,2010,266500
1458,20,68.0,9717,5,6,1950,1996,0.0,49,1029,...,366,0,112,0,0,0,0,4,2010,142125
1459,20,75.0,9937,5,6,1965,1965,0.0,830,290,...,736,68,0,0,0,0,0,6,2008,147500

In [10]:
from numpy.linalg import norm

def center_normalize_df (dataframe):
    
    for column in dataframe:
        dataframe[column] = dataframe[column] - np.mean(dataframe[column])
        dataframe[column] = dataframe[column] / norm(dataframe[column])
    
    return dataframe

In [11]:
 #lasso with lasso cv

X_lasso = df_cont.loc[:, df_cont.columns != 'SalePrice']
y = df_cont['SalePrice']

from sklearn.model_selection import KFold
from sklearn.linear_model import LassoCV

cv = KFold(n_splits=10, shuffle=True, random_state=10)
model = LassoCV(cv=cv)
lassocv = model.fit(X_lasso, y)

B_lasso = lassocv.coef_
B_lasso = np.insert(B_lasso, 0, lassocv.intercept_, axis=0)

print('The Coef are')
print(B_lasso)
#print('\nlambda best is = %f' % lassocv.alpha_)

The Coef are
[-8.40701334e+05 -0.00000000e+00 -0.00000000e+00  2.87183698e-01
  0.00000000e+00  0.00000000e+00  3.11559804e+02  1.14204873e+02
  3.73687130e+01  1.21999590e+01 -0.00000000e+00  0.00000000e+00
  3.33621357e+01  0.00000000e+00  1.94907667e+00 -0.00000000e+00
  6.43889570e+01  0.00000000e+00 -0.00000000e+00  0.00000000e+00
  0.00000000e+00 -0.00000000e+00 -0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  6.80710647e+01
  2.93259701e+01  0.00000000e+00 -0.00000000e+00  0.00000000e+00
  0.00000000e+00 -0.00000000e+00 -1.43596894e-01  0.00000000e+00
 -0.00000000e+00]

In [12]:
df_cont2 =  df_cont.loc[:, df_cont.columns != 'SalePrice'] * lassocv.coef_
df_cont2

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold
0,-0.0,-0.0,2426.702247,0.0,0.0,624054.286684,228752.360983,7324.267751,8613.171027,-0.0,...,37302.943464,0.000000,0.0,-0.0,0.0,0.0,-0.0,-0.000000,0.0,-0.0
1,-0.0,-0.0,2756.963500,0.0,0.0,615642.171986,225668.829407,0.000000,11931.559865,-0.0,...,31312.689769,8739.139076,0.0,-0.0,0.0,0.0,-0.0,-0.000000,0.0,-0.0
2,-0.0,-0.0,3230.816602,0.0,0.0,623431.167077,228638.156110,6053.731509,5929.180056,-0.0,...,41387.207347,0.000000,0.0,-0.0,0.0,0.0,-0.0,-0.000000,0.0,-0.0
3,-0.0,-0.0,2742.604315,0.0,0.0,596637.023964,224983.600168,0.000000,2635.191136,-0.0,...,43701.623548,0.000000,0.0,-0.0,0.0,0.0,-0.0,-0.000000,0.0,-0.0
4,-0.0,-0.0,4095.239532,0.0,0.0,623119.607273,228409.746363,13079.049556,7990.973120,-0.0,...,56907.410102,5630.586250,0.0,-0.0,0.0,0.0,-0.0,-0.000000,0.0,-0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,-0.0,-0.0,2273.633336,0.0,0.0,622808.047470,228409.746363,0.000000,0.000000,-0.0,...,31312.689769,0.000000,0.0,-0.0,0.0,0.0,-0.0,-0.000000,0.0,-0.0
1456,-0.0,-0.0,3783.645220,0.0,0.0,616265.291593,227039.287885,4446.876849,9637.967580,-0.0,...,34035.532358,10234.763549,0.0,-0.0,0.0,0.0,-0.0,-0.000000,0.0,-0.0
1457,-0.0,-0.0,2596.714997,0.0,0.0,604737.578859,229094.975603,0.000000,3354.988715,-0.0,...,17153.908308,0.000000,0.0,-0.0,0.0,0.0,-0.0,-358.992235,0.0,-0.0
1458,-0.0,-0.0,2790.563993,0.0,0.0,607541.617092,227952.926871,0.000000,597.797989,-0.0,...,16337.055532,10733.305039,0.0,-0.0,0.0,0.0,-0.0,-0.000000,0.0,-0.0
1459,-0.0,-0.0,2853.744406,0.0,0.0,612215.014146,224412.575802,0.000000,10125.965939,-0.0,...,18787.613862,21583.913959,0.0,-0.0,0.0,0.0,-0.0,-0.000000,0.0,-0.0

In [13]:
df_cont2 = df_cont2.loc[:, (df_cont2 != 0).any(axis=0)]
df_cont2

,LotArea,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,TotalBsmtSF,2ndFlrSF,GrLivArea,GarageArea,WoodDeckSF,MiscVal
0,2426.702247,624054.286684,228752.360983,7324.267751,8613.171027,28557.988119,1664.511472,110105.116433,37302.943464,0.000000,-0.000000
1,2756.963500,615642.171986,225668.829407,0.000000,11931.559865,42103.015195,0.000000,81258.863707,31312.689769,8739.139076,-0.000000
2,3230.816602,623431.167077,228638.156110,6053.731509,5929.180056,30693.164801,1687.900392,114998.677164,41387.207347,0.000000,-0.000000
3,2742.604315,596637.023964,224983.600168,0.000000,2635.191136,25221.774554,1473.501959,110555.839132,43701.623548,0.000000,-0.000000
4,4095.239532,623119.607273,228409.746363,13079.049556,7990.973120,38199.645323,2052.377728,141526.927439,56907.410102,5630.586250,-0.000000
...,...,...,...,...,...,...,...,...,...,...,...
1455,2273.633336,622808.047470,228409.746363,0.000000,0.000000,31794.115278,1352.659206,106048.612144,31312.689769,0.000000,-0.000000
1456,3783.645220,616265.291593,227039.287885,4446.876849,9637.967580,51444.413178,0.000000,133478.307817,34035.532358,10234.763549,-0.000000
1457,2596.714997,604737.578859,229094.975603,0.000000,3354.988715,38433.180273,2245.336318,150670.159330,17153.908308,0.000000,-358.992235
1458,2790.563993,607541.617092,227952.926871,0.000000,597.797989,35964.382235,0.000000,69411.295623,16337.055532,10733.305039,-0.000000
1459,2853.744406,612215.014146,224412.575802,0.000000,10125.965939,41902.842381,0.000000,80872.529965,18787.613862,21583.913959,-0.000000

In [14]:
def outliers (dataframe):
    
    for column in dataframe:
        Q1 = dataframe[column].quantile(0.25)
        Q3 = dataframe[column].quantile(0.75)
        IQR = Q3 - Q1
        Lower_Bound = Q1 - 1.5*IQR
        Upper_Bound = Q3 + 1.5*IQR
        
        for i in np.linspace(0,len(dataframe[column])-1, len(dataframe[column])):
            if dataframe[column][i] < Lower_Bound:
                dataframe[column][i] = Q1
            elif dataframe[column][i] > Upper_Bound:
                dataframe[column][i] = Q3
                
    return dataframe

In [15]:
np.linspace(0,len(df_cont2['LotArea'])-1,len(df_cont2['LotArea']))

array([0.000e+00, 1.000e+00, 2.000e+00, ..., 1.457e+03, 1.458e+03,
       1.459e+03])

In [16]:
dr_cont2 = outliers(df_cont2)
df_cont2

C:\Users\Woon\AppData\Local\Temp\ipykernel_25712\1406083057.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe[column][i] = Q3
C:\Users\Woon\AppData\Local\Temp\ipykernel_25712\1406083057.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe[column][i] = Q1

,LotArea,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,TotalBsmtSF,2ndFlrSF,GrLivArea,GarageArea,WoodDeckSF,MiscVal
0,2426.702247,624054.286684,228752.360983,7324.267751,8613.171027,28557.988119,1664.511472,110105.116433,37302.943464,0.000000,-0.0
1,2756.963500,615642.171986,225668.829407,0.000000,11931.559865,42103.015195,0.000000,81258.863707,31312.689769,8739.139076,-0.0
2,3230.816602,623431.167077,228638.156110,6053.731509,5929.180056,30693.164801,1687.900392,114998.677164,41387.207347,0.000000,-0.0
3,2742.604315,596637.023964,224983.600168,0.000000,2635.191136,25221.774554,1473.501959,110555.839132,43701.623548,0.000000,-0.0
4,4095.239532,623119.607273,228409.746363,13079.049556,7990.973120,38199.645323,2052.377728,141526.927439,56907.410102,5630.586250,-0.0
...,...,...,...,...,...,...,...,...,...,...,...
1455,2273.633336,622808.047470,228409.746363,0.000000,0.000000,31794.115278,1352.659206,106048.612144,31312.689769,0.000000,-0.0
1456,3783.645220,616265.291593,227039.287885,4446.876849,9637.967580,51444.413178,0.000000,133478.307817,34035.532358,10234.763549,-0.0
1457,2596.714997,604737.578859,229094.975603,0.000000,3354.988715,38433.180273,2245.336318,150670.159330,17153.908308,0.000000,-0.0
1458,2790.563993,607541.617092,227952.926871,0.000000,597.797989,35964.382235,0.000000,69411.295623,16337.055532,10733.305039,-0.0
1459,2853.744406,612215.014146,224412.575802,0.000000,10125.965939,41902.842381,0.000000,80872.529965,18787.613862,4926.762969,-0.0